spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
    password: # redis 密码
    database: 1
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 500
        min-idle: 0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/happyshare?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 111111 # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    resources:
      add-mappings: true
  mail:
    default-encoding: UTF-8
    host: smtp.163.com # 网站发送邮件邮箱服务 host
    port: 465
    username: ${MAIL_USERNAME} # 邮箱
    password: ${MAIL_PASSWORD} # 验证码
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: 'true'
          socketFactory:
            class: cn.returntmp.happyshare.util.MailSSLSocketFactory
            #            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
          stattls:
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  application:
    name: happyshare

env: dev
wx:
  open:
    componentAppId: #
    componentSecret: #
    componentToken: #
    componentAesKey: #
  mp:
    configs:
      - appId: xxx #微信公众号消息服务器配置的 appId
        secret: xxx #微信公众号消息服务器配置的 secret
        token: xxx #微信公众号消息服务器配置的 token
        aesKey: xxx #微信公众号消息服务器配置的 aesKey
  miniapp:
    configs:
      - appid: #微信小程序消息服务器配置的 appid
        secret: #微信小程序消息服务器配置的 secret
        token: #微信小程序消息服务器配置的 token
        aesKey: #微信小程序消息服务器配置的 EncodingAESKey
        msgDataFormat: JSON
logging:
  file:
    #    path: /logs/happyshare
    path: ${LOGGING_PATH}
  level:
    # 代表 cn.returntmp 包中日志级别仅有在 info 或更高级别日志才会记录
    cn:
      returntmp: info
server:
  port: 8099
  servlet:
    context-path: /happyshare
  max-http-header-size: 1048576
  shutdown: graceful
  tomcat:
    reject-illegal-header: false
version: 1.0
resource:
  domain: http://localhost:3000/   #  网站域名，本地测试时填写前端项目访问地址即可
  file-path: http://localhost:3000/   # 上传文件前缀域名，本地测试时填写前端项目访问地址即可
  pic-path: ${RESOURCE_ICPATH} # 上传文件存储地址，本地测试时填写前端项目路径下的 static 目录即可
  # 这是答题测试的接口地址
  answer-api-url: https://test.rymcu.com/subject/question
openai:
  token: # Open Ai Key
jwt:
  secret: ${JWT_SECRET} # JWT 密钥

